apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: uden-host-config
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
       "system": {
          "system_time": {
            "enabled": true,
            "protocol": "NTP",
            "ntp_config": {
              "server": [
                {
                  "hostname": "3.pool.ntp.org",
                  "command": "SERVER"
                },
                {
                  "hostname": "2.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
